name: dbt_run_integration_test
run-name: ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency: ${{ github.workflow }}

env:
  WAREHOUSE: "${{ vars.WAREHOUSE }}"

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt.yml@main
    with:
      command: >
        dbt test --selector 'integration_tests'
      environment:  ${{ inputs.environment }}
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit