name: dbt_run_scheduled_abis
run-name: dbt_run_scheduled_abis

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@AN-5800/env-vars
    with:
      command_name: Run ABI Models
      command: |
        dbt run -m "fsc_evm,tag:silver_abis" "fsc_evm,tag:gold_abis"
    secrets: inherit