name: dbt_run_streamline_chainhead
run-name: dbt_run_streamline_chainhead

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@AN-5800/env-vars
    with:
      command_name: Run Chainhead Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True}' -m "fsc_evm,tag:streamline_core_complete" "fsc_evm,tag:streamline_core_realtime" "fsc_evm,tag:streamline_core_complete_receipts" "fsc_evm,tag:streamline_core_realtime_receipts"
      command_name_2: Run Chainhead Tests
      command_2: |
        dbt test -m "fsc_evm,tag:chainhead"
    secrets: inherit