name: dbt_test_daily 
run-name: dbt_test_daily

on:
  workflow_dispatch:
    branches:
      - "main"
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@AN-5800/env-vars
    with:
      target: test
      command_name: Build Daily Testing Views
      command: |
        dbt run -m "fsc_evm,tag:daily_test"
      command_name_2: Run Daily Tests
      command_2: |
        dbt test -m "fsc_evm,tag:daily_test"
    secrets: inherit