name: dbt_run_streamline_decoder
run-name: dbt_run_streamline_decoder

on:
  workflow_dispatch:
    branches:
      - "main"
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@AN-5800/env-vars
    with:
      command_name: Run Decoder Models
      command: |
        dbt run -m "fsc_evm,tag:decoded_logs"
    secrets: inherit