name: dbt_run_streamline_decoder_history
run-name: dbt_run_streamline_decoder_history

on:
  workflow_dispatch:
    branches:
      - "main"
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run Decoder Models
      command: |
        dbt run --threads 8 --vars '{"STREAMLINE_INVOKE_STREAMS":True,"WAIT":120}' -m "fsc_evm,tag:streamline_decoded_logs_complete" "fsc_evm,tag:streamline_decoded_logs_history"
    secrets: inherit